Repository MLH-Fellowship/0.5.1-household, pull requests merged in 2020-06, with the labels that each got.

#11 Add models skeleton
  app/models.py
Labels: database

#13 Add Sendgrid integration.
  app/auth.py
  app/templates/base.jinja
  app/templates/email_verify.jinja
  app/templates/password_email_reset.jinja
  app/templates/password_reset.jinja
  app/utils.py
  requirements.txt
Labels: feature

#27 Add table relationships
  app/models.py
Labels: database

#28 Add house routes
  app/__init__.py
  app/app.db
  app/auth.py
  app/house.py
  app/models.py
  app/test_e2e.py
  app/utils.py
  migrations/versions/33a879a0d3d9_.py
  migrations/versions/b6a23ea4f451_.py
Labels: api

#32 Add get and update house routes + test.
  app/app.db
  app/house.py
  app/test_e2e.py
Labels: api

#25 Add user_task endpoint
  app/__init__.py
  app/models.py
  app/user_task.py
Labels: api

#33 Add add task route.
  .gitignore
  app/house.py
  app/models.py
  app/schedule.py
Labels: api

#34 Add get all tasks.
  app/app.db
  app/house.py
  app/test_e2e.py
Labels: api

#35 Add task routes.
  app/__init__.py
  app/task.py
  app/test_e2e.py
  app/user_task.py
Labels: api

#39 Add custom expiry time + test
  app/auth.py
  app/test_e2e.py
Labels: api

#41 Add hotfix for houses retrieval data
  app/house.py
  app/test_e2e.py
Labels: api, hotfix

#43 Add username retrieval to login
  app/auth.py
  app/test_e2e.py
Labels: api, hotfix

#47 Add skeleton Rust task handler.
  .github/workflows/ci.yml
  .gitignore
  Cargo.lock
  Cargo.toml
  Procfile
  app/__init__.py
  app/house.py
  app/models.py
  app/schedule.py
  data/Cargo.toml
  data/migrations/00000000000000_diesel_initial_setup/down.sql
  data/migrations/00000000000000_diesel_initial_setup/up.sql
  data/migrations/2020-06-05-062636_initial_models/down.sql
  data/migrations/2020-06-05-062636_initial_models/up.sql
  data/src/lib.rs
  data/src/schema.rs
  diesel.toml
  migrations/versions/128df5b24b26_.py
  migrations/versions/9b5070da5d8f_.py
  requirements.txt
  worker.py
  worker/Cargo.toml
  worker/src/main.rs
Labels: api, worker
